### ISSUE TITLE
Plugin won't load with recent geometry changes

### ISSUE THREAD

**Issue by desyncr** [desyncr/geometry-dir-info-prompt#6]
Not sure which has caused this behavior either geometry or the plugin doing something weird. See #4

**Comment by desyncr** [comment]
Should be fixed with https://github.com/fribmendes/geometry/pull/160

**Comment by mustaqimM** [comment]
@desyncr I'm now on `v1.0.0` on geometry but I have to manually invoke `source ~/.zshrc` to make it appear:
```bash
▲ ~/Downloads                                      master :: 16m :: ⬢ (⚓ ) :: 22 files, 75K
```
And it also has some kind of anchor glyph showing up even with other fonts.

**Comment by desyncr** [comment]
It seems it the [docker machine](https://github.com/fribmendes/geometry/tree/master/plugins/docker_machine) plugin. Check if it's enabled for some reason with:

    $ geometry_plugin_list
    exec_time
    git
    node
    geo_prompt
    dir_info

**Comment by desyncr** [comment]
Should be solved no latests geometry! Closing for now. @mustaqimM If you got still issues with `docker_machine` plugin please open up an issue so we can follow up on that issue.
